name: Validate Pull Requests

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.trim();
            const desc = pr.body ? pr.body.trim() : "";

            const validPrefixes = ['feat:', 'fix:', 'chore:', 'docs:', 'test:', 'refactor:'];
            const isValidTitle = validPrefixes.some(prefix => title.startsWith(prefix));
            const hasReference = /#[0-9]+/.test(desc);

            if (!isValidTitle) {
              core.setFailed("❌ PR title must start with a valid prefix: feat:, fix:, chore:, etc.");
            }
            if (desc.length < 20) {
              core.setFailed("❌ PR description must be at least 20 characters.");
            }
            if (!hasReference) {
              core.setFailed("❌ PR description must reference at least one issue (e.g., Closes #12).");
            }